version: '1.0'
services:
    mysql_dev:
        container_name: mysql_dev
        image: mysql:8.0
        command: mysqld --sql_mode="IGNORE_SPACE,STRICT_TRANS_TABLES"
        env_file:
            - ../../../../env/.env.dev
        environment:
            - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE: ${MYSQL_DATABASE}
            - MYSQL_USER: ${MYSQL_USER}
            - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '${MYSQL_PORT}:3306'
        restart: unless-stopped
        volumes:
            - mysql_dev:/var/lib/mysql
        networks:
            - dev
